server:
  compression:
    enabled: true # 开启gzip压缩
  port: 8360
  #ssl:
  #  key-store: classpath:www.com.jks
  #  key-store-password: 2Ef
  #  key-store-type: JKS

spring:
  application:
    name: erp-api
  datasource:
    url: jdbc:mysql:///erp?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    timeout: 5000
#    database: 0
  servlet:
    multipart:
      max-file-size: 8MB # 单次最大请求文件大小
      max-request-size: 24MB # 总请求最大文件大小
#  rabbitmq:
#    host: 106.52.255.36
#    port: 5672
#    username: admin
#    password: admin
#    virtual-host: nlgc-api # 虚拟 host

mybatis:
  type-aliases-package: org.kuro.erp.model.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启控制台打印 sql
    map-underscore-to-camel-case: true                    # 下划线转驼峰配置
    use-generated-keys: true                              # 返回主键
  mapper-locations: classpath:mapper/*.xml                # 配置扫描

sa-token:
  token-name: Authorization
  is-concurrent: false    # 是否允许同一账号并发登录
  is-share: false         # 多人登录同一账号时，是否共用一个token
  token-style: random-64  # token风格
  is-log: false           # 是否输出操作日志
  is-read-body: false     # 是否尝试从请求体里读取token
  is-read-cookie: false   # 是否尝试从cookie里读取token
  is-read-head: true      # 是否尝试从header里读取token
  is-print: false         # 是否在初始化配置时打印版本字符画

pagehelper:
  support-methods-arguments: true
  helper-dialect: mysql

#knife4j:
#  enable: true
#  basic:
#    enable: true
#    username: erp
#    password: 123456

logging:
  level:
    root: warn
    org.blog: info
  file:
    name: log/erp.log

ignored: |
  /v2/*,/favicon.ico,/swagger-resources/**,/druid/**,/swagger-ui.html,/webjars/**,
  /*.html,/img/**,/css/**,/js/**,/fonts/**,
  /api/sys/login
